"""
Run the Python-buildable thesis table pipeline.

This script builds CSV-only Python-derived model tables from the current
processed data. R-dependent ARMAX-EGARCHX and TVP-VAR outputs are generated by
their model-specific scripts once those inputs exist.
are generated by their model-specific scripts once those inputs exist.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT / "code" / "src"))

import pandas as pd  # noqa: E402
from thesis.paths import FIGURES_DIR, PROCESSED_DATA_DIR, PROJECT_ROOT as THESIS_ROOT, TABLES_DIR  # noqa: E402
from thesis.table_output import write_dataframe  # noqa: E402
from thesis.table_registry import ensure_output_structure  # noqa: E402
from thesis.tables.common import add_sentiment_measures, read_daily_time_series  # noqa: E402
from thesis.tables.data_inventory import table_01_data_inventory  # noqa: E402
from thesis.tables.egarch_eda import (  # noqa: E402
    make_egarch_eda_figures,
    table_02a_full_sample_descriptives,
    table_02b_restricted_sample_descriptives,
    table_03_combined_pre_estimation_diagnostics,
)
from thesis.tables.expectation_adjusted_sentiment import (  # noqa: E402
    expectation_adjusted_dataset,
    expectation_adjusted_descriptives,
    expectation_adjusted_pre_estimation_diagnostics,
    table_21_correlation_matrix_multicollinearity,
    table_22_orthogonalization_regression_results,
    table_23_residual_ais_validation,
)
from thesis.tables.model_inputs import prepare_egarch_full_input, prepare_egarch_restricted_input  # noqa: E402
from thesis.tables.sentiment_dfm_em import (  # noqa: E402
    dfm_em_dataset,
    dfm_em_pre_estimation_diagnostics,
    make_dfm_em_factor_comparison_plots,
    table_15_daily_sentiment_descriptives_by_source,
    table_17_dynamic_factor_results,
    table_18_ais_construction_validation,
)
from thesis.tables.roberta_diagnostics import (  # noqa: E402
    table_roberta_count_descriptives,
    table_roberta_count_descriptives_shifted,
    table_roberta_daily_counts,
    table_roberta_daily_counts_shifted,
    table_roberta_extreme_sentiment,
    table_roberta_label_distribution,
    table_roberta_validation_sample,
)


DEFAULT_TIME_SERIES_CSV = PROCESSED_DATA_DIR / "combined_time_series.csv"
DEFAULT_SENTIMENT_RECORDS_CSV = PROCESSED_DATA_DIR / "combined_dedup_roberta_sentiment.csv"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Python-buildable thesis tables.")
    parser.add_argument("--time-series-csv", type=Path, default=DEFAULT_TIME_SERIES_CSV)
    parser.add_argument("--sentiment-records-csv", type=Path, default=DEFAULT_SENTIMENT_RECORDS_CSV)
    parser.add_argument("--skip-figures", action="store_true")
    parser.add_argument("--cov-type", default="HC3")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ensure_output_structure()
    df = read_daily_time_series(args.time_series_csv)
    enriched = add_sentiment_measures(df)
    armax_full = prepare_egarch_full_input(df)
    armax_restricted = prepare_egarch_restricted_input(df)
    eais_coefficients = table_22_orthogonalization_regression_results(df, cov_type=args.cov_type)
    dfm_results = table_17_dynamic_factor_results(df)

    outputs = [
        write_dataframe(table_01_data_inventory(enriched), TABLES_DIR / "01_data_inventory" / "table_01_data_sources_definitions_transformations_availability.csv"),
        write_dataframe(armax_full, TABLES_DIR / "armax_egarchx" / "armax_egarchx_full_dataset.csv"),
        write_dataframe(armax_restricted, TABLES_DIR / "armax_egarchx" / "armax_egarchx_restricted_dataset.csv"),
        write_dataframe(armax_restricted, TABLES_DIR / "armax_egarchx" / "armax_egarchx_dataset.csv"),
        write_dataframe(table_02a_full_sample_descriptives(armax_full), TABLES_DIR / "armax_egarchx" / "armax_egarchx_full_descriptives.csv"),
        write_dataframe(table_02b_restricted_sample_descriptives(armax_restricted), TABLES_DIR / "armax_egarchx" / "armax_egarchx_restricted_descriptives.csv"),
        write_dataframe(table_02b_restricted_sample_descriptives(armax_restricted), TABLES_DIR / "armax_egarchx" / "armax_egarchx_descriptives.csv"),
        write_dataframe(table_03_combined_pre_estimation_diagnostics(armax_full, armax_restricted), TABLES_DIR / "armax_egarchx" / "armax_egarchx_pre_estimation_diagnostics.csv"),
        write_dataframe(dfm_em_dataset(df), TABLES_DIR / "dfm_em" / "dfm_em_dataset.csv"),
        write_dataframe(table_15_daily_sentiment_descriptives_by_source(df), TABLES_DIR / "dfm_em" / "dfm_em_descriptives.csv"),
        write_dataframe(dfm_em_pre_estimation_diagnostics(df), TABLES_DIR / "dfm_em" / "dfm_em_pre_estimation_diagnostics.csv"),
        write_dataframe(dfm_results, TABLES_DIR / "dfm_em" / "dfm_em_results.csv"),
        write_dataframe(dfm_results[dfm_results["metric"].eq("factor_loading")].reset_index(drop=True), TABLES_DIR / "dfm_em" / "dfm_em_coefficients.csv"),
        write_dataframe(table_18_ais_construction_validation(df), TABLES_DIR / "dfm_em" / "dfm_em_post_estimation_diagnostics.csv"),
        write_dataframe(expectation_adjusted_dataset(df), TABLES_DIR / "expectation_adjusted_sentiment" / "expectation_adjusted_sentiment_dataset.csv"),
        write_dataframe(expectation_adjusted_descriptives(df), TABLES_DIR / "expectation_adjusted_sentiment" / "expectation_adjusted_sentiment_descriptives.csv"),
        write_dataframe(expectation_adjusted_pre_estimation_diagnostics(df), TABLES_DIR / "expectation_adjusted_sentiment" / "expectation_adjusted_sentiment_pre_estimation_diagnostics.csv"),
        write_dataframe(table_21_correlation_matrix_multicollinearity(df), TABLES_DIR / "expectation_adjusted_sentiment" / "expectation_adjusted_sentiment_multicollinearity_diagnostics.csv"),
        write_dataframe(eais_coefficients, TABLES_DIR / "expectation_adjusted_sentiment" / "expectation_adjusted_sentiment_coefficients.csv"),
        write_dataframe(_regression_results_summary(eais_coefficients), TABLES_DIR / "expectation_adjusted_sentiment" / "expectation_adjusted_sentiment_results.csv"),
        write_dataframe(table_23_residual_ais_validation(df), TABLES_DIR / "expectation_adjusted_sentiment" / "expectation_adjusted_sentiment_post_estimation_diagnostics.csv"),
    ]

    try:
        sentiment_records = pd.read_csv(args.sentiment_records_csv)
        outputs.extend([
            write_dataframe(table_roberta_daily_counts(sentiment_records), TABLES_DIR / "RoBERTa" / "roberta_daily_counts.csv"),
            write_dataframe(table_roberta_daily_counts_shifted(sentiment_records, df["date"]), TABLES_DIR / "RoBERTa" / "roberta_daily_counts_shifted.csv"),
            write_dataframe(table_roberta_count_descriptives(sentiment_records), TABLES_DIR / "RoBERTa" / "roberta_count_descriptives.csv"),
            write_dataframe(table_roberta_count_descriptives_shifted(sentiment_records, df["date"]), TABLES_DIR / "RoBERTa" / "roberta_count_descriptives_shifted.csv"),
            write_dataframe(table_roberta_validation_sample(sentiment_records, n=100, seed=42), TABLES_DIR / "RoBERTa" / "roberta_validation_sample_100.csv"),
            write_dataframe(table_roberta_extreme_sentiment(sentiment_records, top_n=5), TABLES_DIR / "RoBERTa" / "roberta_extreme_sentiment.csv"),
            write_dataframe(table_roberta_label_distribution(sentiment_records), TABLES_DIR / "RoBERTa" / "roberta_label_distribution.csv"),
        ])
    except Exception as exc:
        print(f"Warning: Could not read sentiment records from {args.sentiment_records_csv}: {exc}")

    if not args.skip_figures:
        outputs.extend(make_egarch_eda_figures(df))
        outputs.extend(make_dfm_em_factor_comparison_plots(df, FIGURES_DIR / "dfm_em"))

    for path in outputs:
        print(path.relative_to(THESIS_ROOT))


def _regression_results_summary(coefficients):
    columns = [
        "specification",
        "dependent_variable",
        "r_squared",
        "adjusted_r_squared",
        "nobs",
        "covariance_type",
    ]
    available = [column for column in columns if column in coefficients.columns]
    return coefficients[available].drop_duplicates().reset_index(drop=True)


if __name__ == "__main__":
    main()
