"""
Run the Python-buildable thesis table pipeline.

This script builds Tables 1-4 and 14-24 from the current processed data. Tables
5-13 and 25-29 depend on R EGARCH/TVP-VAR and connectedness outputs, so those
are generated by their model-specific scripts once those inputs exist.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "code" / "src"))

from thesis.paths import PROCESSED_DATA_DIR, PROJECT_ROOT as THESIS_ROOT  # noqa: E402
from thesis.table_output import write_registered_table  # noqa: E402
from thesis.table_registry import ensure_output_structure  # noqa: E402
from thesis.thesis_tables import (  # noqa: E402
    add_sentiment_measures,
    make_egarch_eda_figures,
    read_daily_time_series,
    table_01_data_inventory,
    table_02_return_sentiment_descriptives,
    table_03_pre_estimation_diagnostics,
    table_04_arma_lag_order_selection,
    table_14_text_data_coverage_by_source,
    table_15_daily_sentiment_descriptives_by_source,
    table_16_sentiment_source_correlation_matrix,
    table_17_pca_results,
    table_18_ais_construction_validation,
    table_19_prediction_market_control_definitions,
    table_20_residual_regression_sample_alignment,
    table_21_correlation_matrix_multicollinearity,
    table_22_orthogonalization_regression_results,
    table_23_residual_ais_validation,
    table_24_raw_ais_versus_residual_ais,
)


DEFAULT_TIME_SERIES_CSV = PROCESSED_DATA_DIR / "combined_time_series.csv"
DEFAULT_SENTIMENT_RECORDS_CSV = PROCESSED_DATA_DIR / "combined_dedup_roberta_sentiment.csv"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Python-buildable thesis tables.")
    parser.add_argument("--time-series-csv", type=Path, default=DEFAULT_TIME_SERIES_CSV)
    parser.add_argument("--sentiment-records-csv", type=Path, default=DEFAULT_SENTIMENT_RECORDS_CSV)
    parser.add_argument("--formats", nargs="+", default=["csv", "tex"], choices=["csv", "tex", "md"])
    parser.add_argument("--skip-figures", action="store_true")
    parser.add_argument("--max-p", type=int, default=3)
    parser.add_argument("--max-q", type=int, default=3)
    parser.add_argument("--cov-type", default="HC3")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ensure_output_structure()
    df = read_daily_time_series(args.time_series_csv)
    enriched = add_sentiment_measures(df)
    sentiment_records = pd.read_csv(args.sentiment_records_csv)

    outputs = []
    outputs.extend(write_registered_table(1, table_01_data_inventory(enriched), formats=args.formats))
    outputs.extend(write_registered_table(2, table_02_return_sentiment_descriptives(enriched), formats=args.formats))
    outputs.extend(write_registered_table(3, table_03_pre_estimation_diagnostics(enriched), formats=args.formats))
    outputs.extend(write_registered_table(4, table_04_arma_lag_order_selection(enriched, max_p=args.max_p, max_q=args.max_q), formats=args.formats))
    outputs.extend(write_registered_table(14, table_14_text_data_coverage_by_source(sentiment_records), formats=args.formats))
    outputs.extend(write_registered_table(15, table_15_daily_sentiment_descriptives_by_source(df), formats=args.formats))
    outputs.extend(write_registered_table(16, table_16_sentiment_source_correlation_matrix(df), formats=args.formats))
    outputs.extend(write_registered_table(17, table_17_pca_results(df), formats=args.formats))
    outputs.extend(write_registered_table(18, table_18_ais_construction_validation(df), formats=args.formats))
    outputs.extend(write_registered_table(19, table_19_prediction_market_control_definitions(), formats=args.formats))
    outputs.extend(write_registered_table(20, table_20_residual_regression_sample_alignment(df), formats=args.formats))
    outputs.extend(write_registered_table(21, table_21_correlation_matrix_multicollinearity(df), formats=args.formats))
    outputs.extend(write_registered_table(22, table_22_orthogonalization_regression_results(df, cov_type=args.cov_type), formats=args.formats))
    outputs.extend(write_registered_table(23, table_23_residual_ais_validation(df), formats=args.formats))
    outputs.extend(write_registered_table(24, table_24_raw_ais_versus_residual_ais(df), formats=args.formats))

    if not args.skip_figures:
        outputs.extend(make_egarch_eda_figures(enriched))

    for path in outputs:
        print(path.relative_to(THESIS_ROOT))


if __name__ == "__main__":
    main()
